import React from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

function Home() {
  const data = [
    { name: 'Dec 18', uv: 4000 },
    { name: 'Dec 19', uv: 3000 },
    { name: 'Dec 20', uv: 2000 },
    { name: 'Dec 21', uv: 2780 },
    { name: 'Dec 22', uv: 1890 },
    { name: 'Dec 23', uv: 2390 },
    { name: 'Dec 24', uv: 3490 },
    { name: 'Dec 25', uv: 0 },
    { name: 'Dec 26', uv: 0 },
    { name: 'Dec 27', uv: 0 },
  ];

  return (
    <main className='main-container'>
      <div className='main-title'>
        <h3>Credit usage</h3>
      </div>

      <div className='charts'>
        <ResponsiveContainer width="200%" height={170}>
          <BarChart
            data={data}
            margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
          >
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="name" />
            <YAxis />
            <Tooltip
              content={({ payload }) => {
                if (payload && payload.length) {
                  const { payload: tooltipPayload } = payload[0];
                  return (
                    <div className="custom-tooltip">
                      <p>Date: {tooltipPayload.name}</p>
                      <p>Usage: {tooltipPayload.uv}</p> {/* Cambio de "Value" a "Usage" */}
                    </div>
                    
                  );
                }
                return null;
              }}
              wrapperStyle={{
                backgroundColor: '#181818', // Color de fondo del tooltip
                color: '#ffffff', // Color del texto del tooltip
                border: '1px solid #C0C0C0', // Borde del tooltip
                padding: '5px', // Espacio interno del tooltip
                borderRadius: '5px', // Redondeo de los bordes del tooltip
              }}
            />
            <Bar dataKey="uv" fill="#396CF5" barSize={15} />
          </BarChart>
        </ResponsiveContainer>
      </div>
      
      <div className="bottom-text">
        <p>Data as per UTC. Usage means length of content (in minutes) generated by ai power.</p>
      </div>
      
      <div className="credit-usage">
        <h3>Credits used: 2/5 minutes (40%)</h3>
        <div className="progress-bar">
          <div className="progress" style={{ width: '40%' }}></div>
        </div>
      </div>
      <div className="additional-text">
        <p>(Credits will reset on Jan 15, 02:45 PM)</p>
      </div>
      <div className="Plan">
        <h3>Plan</h3>
        
      </div>
      <div className="Free">
        <p>Free</p>
      </div>

      <div className="Active">
        <p>(Active since Dec 10, 2023)</p>
        <button className="subscribe-button">Subscribe to ai power</button>
      </div>

   
      
    </main>
  );
}

export default Home;


